---
apiVersion: v2
name: edc-dataplane
description: EDC Data-Plane
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-dataplane
type: application
appVersion: "sha-7ae9e4c"
version: 0.0.1
maintainers: []
