---
apiVersion: v2
name: edc-controlplane
description: EDC Control-Plane
home: https://github.com/catenax-ng/product-edc/deployment/helm/edc-controlplane
type: application
appVersion: "sha-be038a7"
version: 0.0.2
maintainers: []
